package com.ericflo.winnow.classifier.local

import com.ericflo.winnow.classifier.message.Category
import java.io.File
import java.util.Locale

/**
 * Builds the bundled model: `./gradlew :classifier:trainLocalModel`.
 *
 * 1. Holds out 20% of the corpus, trains on the rest, and fits the temperature on the
 *    held-out part.
 * 2. Trains the shipped model on the whole corpus with that temperature.
 * 3. Writes the model and a report: held-out and evaluation-set scores.
 */
fun main(args: Array<String>) {
    val (corpusDir, evalFile, modelFile, reportFile) = args.map(::File)
    val result = LocalModelBuild.run(corpusDir, evalFile)
    modelFile.parentFile.mkdirs()
    modelFile.outputStream().use(result.model::write)
    reportFile.writeText(result.report)
    println(result.report)
}

object LocalModelBuild {
    class Result(val model: LocalModel, val report: String)

    fun trainer() = LocalModelTrainer(Corpus.classes)

    fun run(corpusDir: File, evalFile: File): Result {
        val corpus = Corpus.load(corpusDir)
        val classes = Corpus.classes
        val (train, heldOut) = Corpus.split(corpus, 0.2)
        val probe = trainer().train(train.map { it.example(classes) })
        val temperature = LocalModelTrainer.calibrate(probe, heldOut.map { it.example(classes) })
        val calibratedProbe = LocalModel(classes, probe.buckets, probe.weights, probe.bias, temperature)

        val full = trainer().train(corpus.map { it.example(classes) })
        val model = LocalModel(classes, full.buckets, full.weights, full.bias, temperature)
        val evaluation = loadEval(evalFile)

        val report = buildString {
            appendLine("# On-device model report")
            appendLine()
            appendLine("Generated by `./gradlew :classifier:trainLocalModel`. Do not edit by hand.")
            appendLine()
            appendLine("- Corpus: ${corpus.size} messages (" + Category.entries.joinToString(", ") { c -> "${c.key} ${corpus.count { it.category == c }}" } + ")")
            appendLine("- Temperature: $temperature (fit on the held-out 20%)")
            appendLine()
            appendLine("## Held-out 20% of the corpus (model trained on the other 80%)")
            appendLine()
            append(Metrics.of(calibratedProbe, heldOut).table())
            appendLine()
            appendLine("## Evaluation set (`training/eval.tsv`, never trained on; shipped model)")
            appendLine()
            append(Metrics.of(model, evaluation).table())
        }
        return Result(model, report)
    }

    /** `category<TAB>sender<TAB>body` lines, never used for training. */
    fun loadEval(file: File): List<LabeledText> =
        file.readLines().filter { it.isNotBlank() && !it.startsWith("#") }.map { line ->
            val (category, sender, body) = line.split('\t', limit = 3)
            LabeledText(Category.fromKey(category) ?: error("Unknown category $category"), sender, body)
        }
}

/** Accuracy, per-category precision and recall, and the mistakes that matter most. */
class Metrics(private val rows: List<Pair<LabeledText, LocalPrediction>>) {
    val accuracy: Double get() = rows.count { (t, p) -> t.category == p.category }.toDouble() / rows.size

    /** Wanted messages (personal or transactional) the default actions would have filtered. */
    val wantedFiltered: List<LabeledText>
        get() = rows.filter { (t, p) ->
            t.category.defaultAction == com.ericflo.winnow.classifier.message.Action.ALLOW &&
                p.category.defaultAction == com.ericflo.winnow.classifier.message.Action.FILTER
        }.map { it.first }

    fun table(): String = buildString {
        appendLine("Accuracy: ${pct(accuracy)} of ${rows.size}. Wanted messages that would be filtered: ${wantedFiltered.size}.")
        appendLine()
        appendLine("| Category | Precision | Recall | Count |")
        appendLine("|---|---|---|---|")
        Category.entries.forEach { c ->
            val predicted = rows.count { it.second.category == c }
            val actual = rows.count { it.first.category == c }
            val right = rows.count { it.first.category == c && it.second.category == c }
            appendLine("| ${c.label} | ${if (predicted == 0) "–" else pct(right.toDouble() / predicted)} | ${if (actual == 0) "–" else pct(right.toDouble() / actual)} | $actual |")
        }
        appendLine()
        appendLine("| Confidence at least | Share of messages | Correct |")
        appendLine("|---|---|---|")
        listOf(0.5, 0.85, 0.9, 0.95).forEach { threshold ->
            val sure = rows.filter { it.second.confidence >= threshold }
            val correct = sure.count { (t, p) -> t.category == p.category }
            appendLine("| ${pct(threshold)} | ${pct(sure.size.toDouble() / rows.size)} (${sure.size}) | ${if (sure.isEmpty()) "–" else pct(correct.toDouble() / sure.size)} |")
        }
        val wrong = rows.filter { (t, p) -> t.category != p.category }
        if (wrong.isNotEmpty()) {
            appendLine()
            appendLine("Mistakes:")
            appendLine()
            wrong.forEach { (t, p) -> appendLine("- ${t.category.key} → ${p.category.key} (${pct(p.confidence)}): ${t.body.take(90)}") }
        }
    }

    companion object {
        fun of(model: LocalModel, items: List<LabeledText>): Metrics {
            val classifier = OnDeviceClassifier(model)
            return Metrics(items.map { it to classifier.classify(com.ericflo.winnow.classifier.message.InboundMessage(it.sender, it.body)) })
        }

        private fun pct(x: Double) = String.format(Locale.US, "%.0f%%", x * 100)
    }
}
